{
  "hash": "36e33c72cc45354771985ba8bab80c6a",
  "result": {
    "engine": "knitr",
    "markdown": "# DIA spike-in study: DIA-NN DIA dataset\n\n\n::: {.cell}\n\n:::\n\n\nThis chapter explains the main concepts for statistical analysis of\n(DIA) proteomics data using `msqrob2`. To illustrate these concepts, we will\nuse using a publicly available spike-in study published by Staes et al. [@Staes2024]. \nThey spiked digested UPS proteins in a yeast digested background at the following ratio's (yeast:ups ratio 10:1, 10:2, 10:4, 10:8, 10:10).\nHere we will use a subset of the data, i.e. dilutions 10:2, 10:4 and 10:8. \nWe will use output of the search engine DIA-NN 2.2.0. \nThe main search output for this DIA-NN version was stored in the report.parquet file in the DIA-NN output directory, which can be found under data/spikein248-staesetal2024.parquet\n\n# Background\n\n## Challenges{#sec-dia_challenges}\n\nBehind this workflow lies several challenges that will affect the data\nmodelling:\n\n- MS-based proteomics does not measure proteins directly, but their \nconstituting **peptide ions**. The protein-level information needs\nto be reconstructed from the ion data. In this tutorial, we will\nstart from the precursor-level data, which has been constructed from the ion\ndata by DIA-NN.\n- All peptides do not ionise with the same efficiency. Poor \nionisation will lead to reduced signal as less ions will hit the\ndetector, hence leading to a huge variability in intensity among\ndifferent peptide species, even when they originate from the same\nprotein.\n- The identification step is not trivial and prone to \nerrors^[Improving peptide identification is outside the scope of\nthis tutorial]. PSM misidentification leads to the assignment of a\nquantitative values from another peptide with likely another\nionisation efficiency and relative abundance. Hence this misassigned\nvalues often lead to outliers.\n- Moreover, there is a widespread data missingness, which is often related to the\nunderlying quantification value. This phenomenon is known as\nmissingness not at random. Next to that, many reasons can lead to\nions not being identified irrespective of their \nquantification value leading to missingness that is not related to\nits quantitative value. This is referred to as missingness \ncompletely at random. The missingness issue is not negligible as we shall see upon reading the data.\n- Identification issues lead to unbalanced peptide missingness\nacross samples, and the patterns of missing values are potentially\ndifferent for every peptide, highlighting the need for an\nautomatised solution that is robust against missing values.\n- Technical variations during the experiment can lead to systematic \nfluctuations across samples. The most obvious reason is when\ndifferent sample amounts are injected into the instruments, due to\nsmall pipetting inconsistencies for instance. However, these\ndifferences lead to unwanted variation that should be discarded when\nanswering biological questions.\n\n## DIA workflow\n\nDIA-NN provides multiple quantifications, e.g. derived from the MS1 or MS2 spectra, and at precursor or protein (protein group) level. The term 'precursor' refers to a charged peptide species and is the basic unit of identification and quantification in DIA. Hence, in the context of DIA we refer to a precursor table, instead of to a PSM table in DDA. \n\nExamples of different quantities are:\n\n- raw MS1 area: Ms1.Area, normalised MS1 Area: Ms1.Normalised, MS2 Precursor quantities: Precursor.Quantity, Normalised MS2 Precursor quantities: Precursor.Normalised, etc., which are all at the precursor level \n- MS2 based summary at the protein (protein group)-level: PG.MaxLFQ\n\nHere, we will use the `Precursor.Quantity` column.\n\n## Experimental context \n\nThis chapter explains how to analyse a proteomics data set that has \nbeen generated using data independent acquisition (DIA). We will again\nuse an in-house spike-in study to illustrate the analysis.\nThe DIA case-study is a subset of Staes et al. [@Staes2024]. They spiked digested UPS proteins in yeast at the following ratio's (yeast:ups ratio 10:1, 10:2, 10:4, 10:8, 10:10) in a yeast digest background.\n\nEach sample was analyzed in triplicate using an\nUltimate 3000 RSLC ProFlow nano-LC system in-line\nconnected to a Q Exactive HF BioPharma mass spectrometer\n(Thermo). \n\nHere, we will only use the data of the samples from the middle 3 spike-in ratio's (2,4 and 8) that were searched using DIA-NN 2.2.0. The main search output for this DIA-NN version is stored in the report.parquet file in the DIA-NN output directory.\n\n# Load packages\n\nWe load the `msqrob2` package, along with additional packages for\ndata manipulation and visualisation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"QFeatures\")  \nlibrary(\"dplyr\") \nlibrary(\"tidyr\")\nlibrary(\"ggplot2\")\nlibrary(\"msqrob2\")    \nlibrary(\"stringr\")\nlibrary(\"ExploreModelMatrix\")\nlibrary(\"MsCoreUtils\") \nlibrary(\"matrixStats\")\nlibrary(\"patchwork\")\nlibrary(\"kableExtra\")\nlibrary(\"ComplexHeatmap\")\nlibrary(\"scater\")\n```\n:::\n\n\n## Parallelisation {#sec-parallel}\n\n`msqrob2` can parallelise computations during the model estimation\nto improve speed. However, we will disable parallelisation to ensure\nthis vignette can be run regardless of hardware. Parallelisation is\ncontrolled using the `BiocParallel` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"BiocParallel\")\nregister(SerialParam())\n```\n:::\n\n\nIf you want to use `msqrob2` with parallelisation enabled and using\n4 cores, you can run the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregister(MulticoreParam(workers = 4))\n```\n:::\n\n\nBe mindful that, while parallelisation can improve speed, it will also\nconsume more RAM because part of the data will be copied multiple\ntimes over your different workers. If you experience crashes because\nyou exceeded the amount of available RAM on your machine, you should\nreduce the number of requested workers.\n\n# Data\n\n## Precursor table\n\nWe load the output from DIA-NN parquet file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecursorFile <- \"data/spikein248-staesetal2024.parquet\" \n```\n:::\n\n\n\nWe can import the report.parquet file using the `read_parquet` function from the `arrow` package. \nNote, that older versions of DIA-NN store the output as report.tsv. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecursors <- arrow::read_parquet(precursorFile) # function from the arrow package\n#precursors <- data.table::fread(precursorFile) # For older versions of DIA-NN, where the results are stored as tsv files. Note that the precursorFile then would point to \"report.tsv\" \n```\n:::\n\n\nEach row in the precursor data table is in \"long format\" and contains information about one precursor in a specific run (the table below shows the first 6 rows). \nThe columns contains various descriptors about the precursor, such as its sequence, its charge, run, etc. Some of these columns contain the quantification values, e.g. Ms1.Area, Precursor.Quantity etc. \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Run.Index|Run                                                  |Channel |Precursor.Id        |Modified.Sequence  |Stripped.Sequence | Precursor.Charge| Precursor.Lib.Index| Decoy| Proteotypic| Precursor.Mz|Protein.Ids |Protein.Group |Protein.Names |Genes |       RT|      iRT| Predicted.RT| Predicted.iRT| IM| iIM| Predicted.IM| Predicted.iIM| Precursor.Quantity| Precursor.Normalised| Ms1.Area| Ms1.Normalised| Ms1.Apex.Area| Ms1.Apex.Mz.Delta| Normalisation.Factor| Quantity.Quality| Empirical.Quality| Normalisation.Noise| Ms1.Profile.Corr| Evidence| Mass.Evidence| Channel.Evidence| Ms1.Total.Signal.Before| Ms1.Total.Signal.After| RT.Start|  RT.Stop|      FWHM| PG.TopN| PG.MaxLFQ| Genes.TopN| Genes.MaxLFQ| Genes.MaxLFQ.Unique| PG.MaxLFQ.Quality| Genes.MaxLFQ.Quality| Genes.MaxLFQ.Unique.Quality|   Q.Value|       PEP| Global.Q.Value| Lib.Q.Value| Peptidoform.Q.Value| Global.Peptidoform.Q.Value| Lib.Peptidoform.Q.Value| PTM.Site.Confidence|Site.Occupancy.Probabilities  |Protein.Sites | Lib.PTM.Site.Confidence| Translated.Q.Value| Channel.Q.Value| PG.Q.Value|    PG.PEP| GG.Q.Value| Protein.Q.Value| Global.PG.Q.Value| Lib.PG.Q.Value| Best.Fr.Mz| Best.Fr.Mz.Delta|\n|---------:|:----------------------------------------------------|:-------|:-------------------|:------------------|:-----------------|----------------:|-------------------:|-----:|-----------:|------------:|:-----------|:-------------|:-------------|:-----|--------:|--------:|------------:|-------------:|--:|---:|------------:|-------------:|------------------:|--------------------:|--------:|--------------:|-------------:|-----------------:|--------------------:|----------------:|-----------------:|-------------------:|----------------:|--------:|-------------:|----------------:|-----------------------:|----------------------:|--------:|--------:|---------:|-------:|---------:|----------:|------------:|-------------------:|-----------------:|--------------------:|---------------------------:|---------:|---------:|--------------:|-----------:|-------------------:|--------------------------:|-----------------------:|-------------------:|:-----------------------------|:-------------|-----------------------:|------------------:|---------------:|----------:|---------:|----------:|---------------:|-----------------:|--------------:|----------:|----------------:|\n|         0|B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA   |        |(UniMod:1)AAVTLHLR2 |(UniMod:1)AAVTLHLR |AAVTLHLR          |                2|                   0|     0|           1|     461.7771|P38998      |P38998        |LYS1_YEAST    |LYS1  | 89.48647| 34.21962|     89.64584|      34.32372|  0|   0|            0|             0|          1027105.2|            1018664.5|  1664103|        1650427|     1235652.9|        -0.0019836|            0.9917820|        0.8068524|         0.9587077|          -0.0107658|        0.8455485| 2.328422|     0.6659890|        0.9694718|              1446081536|             1354918656| 89.27837| 89.83672| 0.1471047|       0|  60736892|          0|     60736892|            60736892|         0.9713600|            0.9713600|                   0.9713600| 0.0037350| 0.0346908|          6e-07|     1.8e-06|           0.0058624|                  0.0006297|               0.0004264|                   1|(UniMod:1){1.000000}AAVTLHLR2 |[P38998:nA2]  |                       1|                  0|               0|  0.0003065| 0.0006127|  0.0003067|       0.0003116|         0.0002956|      0.0002814|   639.3937|       -0.0043335|\n|         1|B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA   |        |(UniMod:1)AAVTLHLR2 |(UniMod:1)AAVTLHLR |AAVTLHLR          |                2|                   0|     0|           1|     461.7771|P38998      |P38998        |LYS1_YEAST    |LYS1  | 88.51812| 34.21962|     88.65327|      34.23263|  0|   0|            0|             0|          1686047.0|            1473639.0|  2225964|        1945538|     2138060.2|        -0.0012512|            0.8740202|        0.8539391|         0.7675559|           0.0606278|        0.9467068| 2.621551|     0.9197075|        0.7442634|              1707504896|             1714693888| 88.38112| 88.65714| 0.1049480|       0|  59386180|          0|     59386180|            59386180|         0.9682981|            0.9682981|                   0.9682981| 0.0000006| 0.0000010|          6e-07|     1.8e-06|           0.0007060|                  0.0006297|               0.0004264|                   1|(UniMod:1){1.000000}AAVTLHLR2 |[P38998:nA2]  |                       1|                  0|               0|  0.0003028| 0.0006007|  0.0003029|       0.0003108|         0.0002956|      0.0002814|   538.3460|       -0.0010986|\n|         2|B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA   |        |(UniMod:1)AAVTLHLR2 |(UniMod:1)AAVTLHLR |AAVTLHLR          |                2|                   0|     0|           1|     461.7771|P38998      |P38998        |LYS1_YEAST    |LYS1  | 88.19032| 34.21962|     88.42429|      33.99163|  0|   0|            0|             0|          1484137.0|            1497021.4|  2156443|        2175164|     1850866.0|        -0.0018616|            1.0086815|        0.8370125|         0.9024460|           0.0352767|        0.9391663| 1.963248|     0.6607722|        0.5847857|              1906061952|             2011915136| 87.98146| 88.39668| 0.1602550|       0|  61945576|          0|     61945576|            61945576|         0.9670781|            0.9670781|                   0.9670781| 0.0022817| 0.0274225|          6e-07|     1.8e-06|           0.0059578|                  0.0006297|               0.0004264|                   1|(UniMod:1){1.000000}AAVTLHLR2 |[P38998:nA2]  |                       1|                  0|               0|  0.0003133| 0.0006259|  0.0003135|       0.0003190|         0.0002956|      0.0002814|   639.3937|        0.0012817|\n|         3|B000278_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA_2 |        |(UniMod:1)AAVTLHLR2 |(UniMod:1)AAVTLHLR |AAVTLHLR          |                2|                   0|     0|           1|     461.7771|P38998      |P38998        |LYS1_YEAST    |LYS1  | 88.94958| 34.21962|     89.25366|      33.75805|  0|   0|            0|             0|          1202390.5|            1186230.2|  1752379|        1728827|     1130526.8|        -0.0038757|            0.9865599|        0.7660662|         0.7737662|           0.0300994|        0.5843989| 2.661267|     0.6917942|        0.8114025|              2323055360|             2137220352| 88.61057| 89.15668| 0.2167290|       0|  61787356|          0|     61787356|            61787356|         0.9639115|            0.9639115|                   0.9639115| 0.0026284| 0.0164647|          6e-07|     1.8e-06|           0.0061239|                  0.0006297|               0.0004264|                   1|(UniMod:1){1.000000}AAVTLHLR2 |[P38998:nA2]  |                       1|                  0|               0|  0.0003246| 0.0006370|  0.0003248|       0.0003308|         0.0002956|      0.0002814|   425.2619|        0.0019226|\n|         5|B000286_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA_2 |        |(UniMod:1)AAVTLHLR2 |(UniMod:1)AAVTLHLR |AAVTLHLR          |                2|                   0|     0|           1|     461.7771|P38998      |P38998        |LYS1_YEAST    |LYS1  | 88.49445| 34.21962|     88.61003|      34.13313|  0|   0|            0|             0|           475073.6|             579242.2|  1481789|        1806699|      777120.9|        -0.0014648|            1.2192687|        0.6968042|         0.7491062|           0.1018161|        0.0000000| 1.700542|     0.3975840|        0.1695192|              1270731776|             1315600640| 88.28562| 88.63584| 0.1518549|       0|  63859400|          0|     63859400|            63859400|         0.9677207|            0.9677207|                   0.9677207| 0.0040565| 0.0318976|          6e-07|     1.8e-06|           0.0077074|                  0.0006297|               0.0004264|                   1|(UniMod:1){1.000000}AAVTLHLR2 |[P38998:nA2]  |                       1|                  0|               0|  0.0003152| 0.0006296|  0.0003154|       0.0003210|         0.0002956|      0.0002814|   639.3937|        0.0092773|\n|         6|B000302_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA_3 |        |(UniMod:1)AAVTLHLR2 |(UniMod:1)AAVTLHLR |AAVTLHLR          |                2|                   0|     0|           1|     461.7771|P38998      |P38998        |LYS1_YEAST    |LYS1  | 88.94778| 34.21962|     89.22704|      33.83727|  0|   0|            0|             0|          1211047.2|            1278841.4|  1902638|        2009148|     1505334.4|        -0.0023804|            1.0559797|        0.8122462|         0.9176636|          -0.0058500|        0.8568795| 2.149787|     0.2013753|        0.9174258|              1576011776|             1611237888| 88.80907| 89.22405| 0.1854964|       0|  57830312|          0|     57830312|            57830312|         0.9690518|            0.9690518|                   0.9690518| 0.0038881| 0.0323859|          6e-07|     1.8e-06|           0.0095169|                  0.0006297|               0.0004264|                   1|(UniMod:1){1.000000}AAVTLHLR2 |[P38998:nA2]  |                       1|                  0|               0|  0.0003108| 0.0006149|  0.0003110|       0.0003160|         0.0002956|      0.0002814|   639.3937|       -0.0004883|\n\n\n:::\n:::\n\n\n## Sample annotation table\n\nThe [sample annotation table](#sec-annotation_table)) is not available\nand can be generated from the run labels, as the researchers included information on the design in the filenames.\n\nWe will make a new data frame with the annotation. \n\n1. We first generate variable `runCol`, that gives an overview of the different runs in the experiment, i.e. the unique names in the column Run of the report file. This is a mandatory column in the annotation file that is required by the `readQFeatures` function that will be used to generate a QFeatures object with the quant data. \n\n2. Next we generate variable `sampleId`, to pinpoint the different samples in the dataset. This can be extracted from the run names as the researchers have stored information on the meta data in the file names for each run. E.g. for run B000282_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA_2 this is the ratio, i.e. ratio04, and the replicate, i.e. _2 after DIA. Note, that the first replicate has no number. \n    \n    a. We first replace the redundant pattern \"DIA\" with an empty character string. \n    b. Next we split the strings according to the pattern \"UPS2\" using the `strsplit` function and\n    c. keep the right part of the string. We do this by looping over the list from `strplit`  with an sapply loop, which takes the output of b. as its first argument, uses the function '[' to subset vector of strings in each list element and uses an optional argument '2' to select the second string of the vector (right part).\n\n3. We make add the variable `ratio` by parsing the variable stringId and\n\n    a. replacing pattern \"ratio\" by an empty string using the `gsub` function\n    b. splitting the output of `gsub` according to pattern \"_\" and \n    c. keeping the left part of the string (first element of the vector of strings in each list item of the substr output)\n    d. converting the output of c to an integer\n    e. converting the ratio into a factor\n\n4. We make add the variable `rep` by parsing the variable stringId, and  \n\n    a. splitting it according to pattern \"_\", \n    b. keeping the right part of the string (second element of the vector of strings in each list item of the substr output)\n    c. replacing NA by 1, as for the first replicate no number was added to the filename\n    d. converting it into a factor\n    \n\n::: {.cell}\n\n```{.r .cell-code}\nannot <- data.frame(runCol = precursors |> \n                       pull(Run) |> \n                       unique() # 1. \n                   ) |>\n    mutate(sampleId = gsub(x = runCol, pattern = \"_DIA\", replacement = \"\") |> #2.a\n               str_split(\"UPS2_\") |> #2.b\n               sapply(`[`, 2) #2.c\n           ) |>\n    mutate(\n           condition =  gsub(\"ratio\", \"\", sampleId) |> #3.a\n               str_split(\"_\") |> #3.b\n               sapply(`[`, 1) |> #3.c\n               as.numeric() |> #3.d\n               as.factor(), #3.e\n           rep = sampleId |> \n               str_split(\"_\") |> #4.a\n               sapply(`[`, 2) |> #4.b\n               replace_na(replace = \"1\") |> #4.c\n               as.factor(), #4.d\n           ratio = condition |> \n             as.character() |> \n             as.double()\n           )\n```\n:::\n\n\n## Convert to QFeatures\n\n`msqrob2` is built around the `QFeatures` class. We refer to the [R\nfor mass spectrometry\nbook](https://rformassspectrometry.github.io/book/sec-quant.html) for\na comprehensive description of the class. In a nutshell, the\n`QFeatures` package provides infrastructure to manage and analyse\nquantitative features from mass spectrometry experiments. It is based\non the `SummarizedExperiment` and `MultiAssayExperiment` classes. It\nleverages the hierarchical structure of proteomics experiments: data\nproteins are composed of peptides, themselves produced by spectra.\nEach piece of information in stored in an individual\n`SummarizedExperiment` object, later referred to as a \"set\".\nThroughout the aggregation and processing of these data, the relations\nbetween sets are tracked and recorded, thus allowing users to easily\nnavigate across spectra, peptide and protein quantitative data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Illustration of the `QFeatures` data class.](figs/QFeatures.png){width=80%}\n:::\n:::\n\n\nThe `readQFeatures()` enables a seamless conversion of tabular data\ninto a `QFeatures` object. We provide the peptide table and the sample\nannotation table. The function will use the `quantCols` column in the\nsample annotation table to understand which columns in `peptides`\ncontain the quantitative values, and automatically link the\ncorresponding sample annotation with the quantitative values. We also\ntell the function to use the `Sequence` column as peptide identifier,\nwhich will be used as rownames. See `?readQFeatures()` for more\ndetails.\n\nFirst, recall that the precursor table is file in long format. \nEvery quantitative column in the precursor table contains\ninformation for multiple runs. Therefore, the function split the table\nbased on the run identifier, given by the `runCol` argument (for\nDIA-NN, that identifier is contained in `run`). \nSo, the\n`QFeatures` object after import will contain as many sets as there are\nruns. \nNext, the function links the annotation table with the PSM data.\nTo achieve this, the annotation table must contain a `runCol` column\nthat provides the run identifier in which each sample has been\nacquired, and this information will be used to match the identifiers\nin the `Run` column of the precursor table. \n\nHere, we will use the `Precursor.Quantity` column as quantification input. \n\nNote, that the \n\n\n::: {.cell}\n\n```{.r .cell-code}\n(spikein_dia <- readQFeatures(assayData = precursors, \n                             colData = annot,\n                             quantCols = \"Precursor.Quantity\",\n                             runCol = \"Run\",\n                             fnames = \"Precursor.Id\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 9 sets:\n\n [1] B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA: SummarizedExperiment with 34471 rows and 1 columns \n [2] B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA: SummarizedExperiment with 35142 rows and 1 columns \n [3] B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA: SummarizedExperiment with 34028 rows and 1 columns \n ...\n [7] B000302_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA_3: SummarizedExperiment with 33091 rows and 1 columns \n [8] B000306_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA_3: SummarizedExperiment with 34472 rows and 1 columns \n [9] B000310_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA_3: SummarizedExperiment with 33724 rows and 1 columns \n```\n\n\n:::\n:::\n\n\nWe now have a `QFeatures` object with 9 sets, one set for each run that are named based on their run name in the runCol.\nThe sample annotations can be retrieved using `colData()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolData(spikein_dia)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(head(colData(spikein_dia)))\n```\n\n::: {.cell-output-display}\n\n\n|                                                     |runCol                                               |sampleId  |condition |rep | ratio|\n|:----------------------------------------------------|:----------------------------------------------------|:---------|:---------|:---|-----:|\n|B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA   |B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA   |ratio02   |2         |1   |     2|\n|B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA   |B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA   |ratio04   |4         |1   |     4|\n|B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA   |B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA   |ratio08   |8         |1   |     8|\n|B000278_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA_2 |B000278_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA_2 |ratio02_2 |2         |2   |     2|\n|B000282_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA_2 |B000282_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA_2 |ratio04_2 |4         |2   |     4|\n|B000286_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA_2 |B000286_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA_2 |ratio08_2 |8         |2   |     8|\n\n\n:::\n:::\n\n\nWe can get a sample annotation directly using the `$` accessor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia$condition\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2 4 8 2 4 8 2 4 8\nLevels: 2 4 8\n```\n\n\n:::\n:::\n\n\nWe can extract the `SummarizedExperiment` object for the `B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA`\nset using double bracket subsetting^[A `QFeatures` object can be seen\nas a special list of `SummarizedExperiment` objects.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia[[\"B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA\"]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: SummarizedExperiment \ndim: 34471 1 \nmetadata(0):\nassays(1): ''\nrownames(34471): (UniMod:1)AAVTLHLR2 (UniMod:1)ADFLLRPIK2 ...\n  YYYELAYPMGISASHK3 YYYITPISSK2\nrowData names(70): Run.Index Run ... Best.Fr.Mz Best.Fr.Mz.Delta\ncolnames(1): B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA\ncolData names(0):\n```\n\n\n:::\n:::\n\n\nBut notice that the sample annotations were not extracted along with\nthe SummarizedExperiment (`colData names(0):`). This can be performed\nusing `getWithColData()`, which extracts the set of interest (like\n`[[]]`) along with all the associated sample annotations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetWithColData(spikein_dia, \"B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: SummarizedExperiment \ndim: 34471 1 \nmetadata(0):\nassays(1): ''\nrownames(34471): (UniMod:1)AAVTLHLR2 (UniMod:1)ADFLLRPIK2 ...\n  YYYELAYPMGISASHK3 YYYITPISSK2\nrowData names(70): Run.Index Run ... Best.Fr.Mz Best.Fr.Mz.Delta\ncolnames(1): B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA\ncolData names(5): runCol sampleId condition rep ratio\n```\n\n\n:::\n:::\n\n\nThe precursor annotations are available for in the corresponding \n`rowData`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrowData(spikein_dia[[\"B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA\"]])\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(head(rowData(spikein_dia[[\"B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA\"]])))\n```\n\n::: {.cell-output-display}\n\n\n|                            | Run.Index|Run                                                |Channel |Precursor.Id                |Modified.Sequence          |Stripped.Sequence | Precursor.Charge| Precursor.Lib.Index| Decoy| Proteotypic| Precursor.Mz|Protein.Ids                            |Protein.Group                          |Protein.Names |Genes    |        RT|      iRT| Predicted.RT| Predicted.iRT| IM| iIM| Predicted.IM| Predicted.iIM| Precursor.Normalised| Ms1.Area| Ms1.Normalised| Ms1.Apex.Area| Ms1.Apex.Mz.Delta| Normalisation.Factor| Quantity.Quality| Empirical.Quality| Normalisation.Noise| Ms1.Profile.Corr| Evidence| Mass.Evidence| Channel.Evidence| Ms1.Total.Signal.Before| Ms1.Total.Signal.After|  RT.Start|   RT.Stop|      FWHM| PG.TopN| PG.MaxLFQ| Genes.TopN| Genes.MaxLFQ| Genes.MaxLFQ.Unique| PG.MaxLFQ.Quality| Genes.MaxLFQ.Quality| Genes.MaxLFQ.Unique.Quality|   Q.Value|       PEP| Global.Q.Value| Lib.Q.Value| Peptidoform.Q.Value| Global.Peptidoform.Q.Value| Lib.Peptidoform.Q.Value| PTM.Site.Confidence|Site.Occupancy.Probabilities                   |Protein.Sites                                | Lib.PTM.Site.Confidence| Translated.Q.Value| Channel.Q.Value| PG.Q.Value|    PG.PEP| GG.Q.Value| Protein.Q.Value| Global.PG.Q.Value| Lib.PG.Q.Value| Best.Fr.Mz| Best.Fr.Mz.Delta|\n|:---------------------------|---------:|:--------------------------------------------------|:-------|:---------------------------|:--------------------------|:-----------------|----------------:|-------------------:|-----:|-----------:|------------:|:--------------------------------------|:--------------------------------------|:-------------|:--------|---------:|--------:|------------:|-------------:|--:|---:|------------:|-------------:|--------------------:|--------:|--------------:|-------------:|-----------------:|--------------------:|----------------:|-----------------:|-------------------:|----------------:|--------:|-------------:|----------------:|-----------------------:|----------------------:|---------:|---------:|---------:|-------:|---------:|----------:|------------:|-------------------:|-----------------:|--------------------:|---------------------------:|---------:|---------:|--------------:|-----------:|-------------------:|--------------------------:|-----------------------:|-------------------:|:----------------------------------------------|:--------------------------------------------|-----------------------:|------------------:|---------------:|----------:|---------:|----------:|---------------:|-----------------:|--------------:|----------:|----------------:|\n|(UniMod:1)AAVTLHLR2         |         0|B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA |        |(UniMod:1)AAVTLHLR2         |(UniMod:1)AAVTLHLR         |AAVTLHLR          |                2|                   0|     0|           1|     461.7771|P38998                                 |P38998                                 |LYS1_YEAST    |LYS1     |  89.48647| 34.21962|     89.64584|      34.32372|  0|   0|            0|             0|              1018664|  1664103|        1650427|       1235653|        -0.0019836|            0.9917820|        0.8068524|         0.9587077|          -0.0107658|        0.8455485| 2.328422|     0.6659890|        0.9694718|              1446081536|             1354918656|  89.27837|  89.83672| 0.1471047|       0|  60736892|          0|     60736892|            60736892|         0.9713600|            0.9713600|                   0.9713600| 0.0037350| 0.0346908|      0.0000006|   0.0000018|           0.0058624|                  0.0006297|               0.0004264|                   1|(UniMod:1){1.000000}AAVTLHLR2                  |[P38998:nA2]                                 |                       1|                  0|               0|  0.0003065| 0.0006127|  0.0003067|       0.0003116|         0.0002956|      0.0002814|   639.3937|       -0.0043335|\n|(UniMod:1)ADFLLRPIK2        |         0|B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA |        |(UniMod:1)ADFLLRPIK2        |(UniMod:1)ADFLLRPIK        |ADFLLRPIK         |                2|                   1|     0|           1|     557.8346|P38768                                 |P38768                                 |PIH1_YEAST    |PIH1     | 121.34409| 76.86208|    121.09219|      77.28922|  0|   0|            0|             0|              5805858|  6862994|        6878766|       5909809|        -0.0009155|            1.0022984|        0.9153399|         0.8982903|          -0.0820856|        0.9530441| 4.035011|     0.9436575|        0.9152272|              2151185664|             2523537408| 121.13556| 121.55209| 0.2078343|       0|   5839721|          0|      5839721|             5839721|         0.9533337|            0.9533337|                   0.9533337| 0.0001971| 0.0008056|      0.0000594|   0.0004220|           0.0038466|                  0.0000434|               0.0004264|                   1|(UniMod:1){1.000000}ADFLLRPIK2                 |[P38768:nA2]                                 |                       1|                  0|               0|  0.0003065| 0.0006127|  0.0003067|       0.0003116|         0.0002956|      0.0002814|   739.5189|        0.0064697|\n|(UniMod:1)ADQENSPLHTVGFDAR2 |         0|B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA |        |(UniMod:1)ADQENSPLHTVGFDAR2 |(UniMod:1)ADQENSPLHTVGFDAR |ADQENSPLHTVGFDAR  |                2|                   2|     0|           1|     899.9214|Q01519                                 |Q01519                                 |COX12_YEAST   |COX12    |  96.37570| 43.68274|     96.40407|      43.26940|  0|   0|            0|             0|              2484560|  4638513|        4181090|       3257204|        -0.0028076|            0.9013858|        0.8505211|         0.8960215|          -0.1175555|        0.1497211| 2.780470|     0.0000000|        0.0000000|              2476784896|             2149216256|  96.09526|  96.51259| 0.2029101|       0|   4200631|          0|      4200631|             4200631|         0.7279488|            0.7279488|                   0.7279488| 0.0001109| 0.0003342|      0.0001535|   0.0000110|           0.0008496|                  0.0001535|               0.0000858|                   1|(UniMod:1){1.000000}ADQENSPLHTVGFDAR2          |[Q01519:nA2]                                 |                       1|                  0|               0|  0.0003065| 0.0006127|  0.0003067|       0.0003116|         0.0002956|      0.0002814|  1112.5847|        0.0003662|\n|(UniMod:1)ADRPAIQLIDEEK2    |         0|B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA |        |(UniMod:1)ADRPAIQLIDEEK2    |(UniMod:1)ADRPAIQLIDEEK    |ADRPAIQLIDEEK     |                2|                   3|     0|           1|     770.4043|Q99287                                 |Q99287                                 |SEY1_YEAST    |SEY1     |  99.30938| 46.84668|     99.22821|      46.72539|  0|   0|            0|             0|             23580588| 41664160|       38337532|      30911908|         0.0007935|            0.9201562|        0.9414624|         0.9643323|          -0.0410851|        0.7397323| 5.575790|     6.7299194|        0.8155769|              3827094528|             3918695680|  99.10566|  99.64997| 0.1995289|       0|  19897200|          0|     19897200|            19897200|         0.9817545|            0.9817545|                   0.9817545| 0.0002359| 0.0013136|      0.0009756|   0.0005324|           0.0010095|                  0.0009756|               0.0005600|                   1|(UniMod:1){1.000000}ADRPAIQLIDEEK2             |[Q99287:nA2]                                 |                       1|                  0|               0|  0.0003065| 0.0006127|  0.0003067|       0.0003116|         0.0002956|      0.0002814|   385.1830|       -0.0030212|\n|(UniMod:1)ADSRDPASDQMQHWK3  |         0|B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA |        |(UniMod:1)ADSRDPASDQMQHWK3  |(UniMod:1)ADSRDPASDQMQHWK  |ADSRDPASDQMQHWK   |                3|                   4|     0|           1|     605.2689|UPS&#124;P04040ups&#124;CATA_HUMAN_UPS |UPS&#124;P04040ups&#124;CATA_HUMAN_UPS |Catalase      |Catalase |  72.52413| 12.41975|     72.42027|      12.41038|  0|   0|            0|             0|             18282968| 38022488|       33889840|      24028186|         0.0015259|            0.8913103|        0.9240255|         0.9132833|          -0.1045958|        0.9351028| 4.820643|     3.4202857|        0.9711437|              1595096064|             1146928256|  72.17480|  72.87411| 0.1191725|       0| 446047008|          0|    446047008|           446047008|         0.9888229|            0.9888229|                   0.9888229| 0.0000007| 0.0000011|      0.0000007|   0.0000005|           0.0000021|                  0.0000005|               0.0000007|                   1|(UniMod:1){1.000000}ADSRDPASDQM{0.000000}QHWK3 |[UPS&#124;P04040ups&#124;CATA_HUMAN_UPS:nA1] |                       1|                  0|               0|  0.0003065| 0.0006127|  0.0003067|       0.0003116|         0.0002956|      0.0002814|   684.2947|       -0.0001831|\n|(UniMod:1)ADYSSLTVVQLK2     |         0|B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA |        |(UniMod:1)ADYSSLTVVQLK2     |(UniMod:1)ADYSSLTVVQLK     |ADYSSLTVVQLK      |                2|                   5|     0|           1|     683.3666|P40040                                 |P40040                                 |THO1_YEAST    |THO1     | 116.96347| 70.92368|    117.21514|      69.98866|  0|   0|            0|             0|              1040754|  2283084|        2449571|       1465530|         0.0042725|            1.0729221|        0.8623313|         0.9079940|          -0.0981701|        0.7081269| 3.002951|     0.0000000|        0.9367919|              1824255872|             1798676736| 116.68488| 117.10079| 0.1046619|       0|  30541228|          0|     30541228|            30541228|         0.9704166|            0.9704166|                   0.9704166| 0.0005245| 0.0044713|      0.0000007|   0.0000007|           0.0056301|                  0.0000005|               0.0000007|                   1|(UniMod:1){1.000000}ADYSSLTVVQLK2              |[P40040:nA2]                                 |                       1|                  0|               0|  0.0003065| 0.0006127|  0.0003067|       0.0003116|         0.0002956|      0.0002814|   687.4399|        0.0006104|\n\n\n:::\n:::\n\n\nWe can also retrieve the quantitative values for each set using \n`assay()`. Here we only show the first 5 rows of the intensity matrix for the first summarized experiment. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nassay(spikein_dia[[1]]) |> head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA\n(UniMod:1)AAVTLHLR2                                                    1027105\n(UniMod:1)ADFLLRPIK2                                                   5792544\n(UniMod:1)ADQENSPLHTVGFDAR2                                            2756378\n(UniMod:1)ADRPAIQLIDEEK2                                              25626726\n(UniMod:1)ADSRDPASDQMQHWK3                                            20512458\n```\n\n\n:::\n:::\n\nNote, that there is only one column, because each run has been stored in a separate summarized experiment. \nWe will join the data of the runs later. \n\nSince we have a `QFeatures` object, we can directly make use of\n`QFeatures`' data preprocessing functionality^[see also the [R for\nmass spectrometry\nbook](https://rformassspectrometry.github.io/book/sec-quant.html)]. A\nmajor advantage of `QFeatures` is it provides the power to build\nhighly modular workflows, where each step is carried out by a\ndedicated function with a large choice of available methods and\nparameters. This means that users can adapt the workflow to their\nspecific use case and their specific needs.\n\n# Data preprocessing{#sec-basic_preprocess}\n\nThe data preprocessing workflow for DIA data is similar to the workflow for DDA-LFQ data, but there are suble differences as we start from precursor level data and have additional columns. \n\n## Encoding missing values\n\nThe first preprocessing step is to correctly encode the missing\nvalues. It is important that missing values are encoded using `NA`.\nFor instance, non-observed values should not be\nencoded with a zero because true zeros (the proteomic feature\nis absent from the sample) cannot be distinguished from technical\nzeros (the feature was missed by the instrument or could not be\nidentified). We therefore replace any zero in the quantitative data\nwith an `NA`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia <- zeroIsNA(spikein_dia, names(spikein_dia))\n```\n:::\n\n\nNote that `msqrob2` can handle missing data without having to rely on\nhard-to-verify imputation assumptions, which is our general recommendation. However, `msqrob2` does not\nprevent users from using imputation, which can be performed with\n`impute()` from the `QFeatures` package. \n\n## Precursor Filtering \n\nFiltering removes low-quality and unreliable precursors that would otherwise introduce noise and artefacts in the data. \n\n### Remove questionable identifications\n\n\nWe apply standard filtering advised by DIA-NN: \n\n1. q-value threshold of 0.01 for the identification of precursors (`Q.Value`) and protein groups (`PG.Q.Value`).\n\n2. Remove precursors that could not be mapped, i.e. when `Precursor.Id` column is an empty string.  \n\n3. Filter decoys, i.e. only keep precursors for which the `Decoy` column equals 0. (Note, that the `Decoy` column is not present in the output of older versions of DIA-NN)\n\n4. Keeping only proteotypic peptides, which map uniquely to a specific protein.\n\nWe use `filterFeatures()` to perform the filtering. It uses\ninformation from the `rowData` and a formula to generate a filter for\neach feature (row) in each set across the object. If the filter\nreturns `TRUE`, the corresponding row is retained, otherwise it is\nremoved. Defining a filter through a formula offers a flexible\napproach, allowing for any customised filter. This dataset requires an\nextensive PSM filtering, which is an ideal use case to demonstrate the\ncustomisation of a filtering workflow.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia <-  spikein_dia |>\n  filterFeatures(~ Q.Value <= 0.01 & #1.\n                     PG.Q.Value <= 0.01 &  #1. \n                     Precursor.Id != \"\" & #2.\n                     Decoy == 0 & #3. (Note, that this filter is not available with previous versions of DIA-NN, as the report.tsv file did not include a Decoy column. So other strategies are needed if Decoys are in the output file.)\n                     Proteotypic == 1) #4.\n```\n:::\n\n\n\nNote, that it is important that the filtering criteria are not distorting the distribution of the test statistics in the downstream analysis for features that are non-DA. \nIt can be shown that filtering will not induce bias results when the filtering criterion is independent of test statistic. The criteria that we proposed above are all based on the results of the identification step, hence, they are independent of the downstream test statistics that will be used to prioritize DA proteins. \n\n### Assay joining\n\nUp to now, the data from different runs were kept in separate assays. We can now join the normalised sets into an precursor set using joinAssays(). Sets are joined by stacking the columns (samples) in a matrix and rows (features) are matched according to a row identifier, here the `Precursor.Id`.\nWe will store the result in the assay with name: `precursor`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(spikein_dia <- joinAssays(\n  x = spikein_dia,\n  i = names(spikein_dia),\n  fcol = \"Precursor.Id\",\n  name = \"precursors\"\n  ))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 10 sets:\n\n [1] B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA: SummarizedExperiment with 32885 rows and 1 columns \n [2] B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA: SummarizedExperiment with 33526 rows and 1 columns \n [3] B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA: SummarizedExperiment with 32434 rows and 1 columns \n ...\n [8] B000306_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA_3: SummarizedExperiment with 32861 rows and 1 columns \n [9] B000310_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA_3: SummarizedExperiment with 32144 rows and 1 columns \n [10] precursors: SummarizedExperiment with 38716 rows and 9 columns \n```\n\n\n:::\n:::\n\n\nWe will again retrieve the quantitative values for each set using \n`assay()`. \nHere we only show the first 5 rows and columns of the intensity matrix and illustrate default subsetting that is possible. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nassay(spikein_dia [[\"precursors\"]])[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA\n(UniMod:1)ADFLLRPIK2                                                5792544.5\n(UniMod:1)ADRPAIQLIDEEK2                                           25626726.0\n(UniMod:1)ADSRDPASDQMQHWK3                                         20512458.0\n(UniMod:1)ADYSSLTVVQLK2                                              970017.8\n(UniMod:1)AEASIEK1                                                 74863536.0\n                           B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA\n(UniMod:1)ADFLLRPIK2                                                  5616620\n(UniMod:1)ADRPAIQLIDEEK2                                             23988660\n(UniMod:1)ADSRDPASDQMQHWK3                                           54094184\n(UniMod:1)ADYSSLTVVQLK2                                               1394431\n(UniMod:1)AEASIEK1                                                   92867856\n                           B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA\n(UniMod:1)ADFLLRPIK2                                                  4810394\n(UniMod:1)ADRPAIQLIDEEK2                                             23561136\n(UniMod:1)ADSRDPASDQMQHWK3                                          156667664\n(UniMod:1)ADYSSLTVVQLK2                                                888451\n(UniMod:1)AEASIEK1                                                   87658384\n                           B000278_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA_2\n(UniMod:1)ADFLLRPIK2                                                    5575437\n(UniMod:1)ADRPAIQLIDEEK2                                               18285408\n(UniMod:1)ADSRDPASDQMQHWK3                                             21354380\n(UniMod:1)ADYSSLTVVQLK2                                                 1183666\n(UniMod:1)AEASIEK1                                                     55235320\n                           B000282_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA_2\n(UniMod:1)ADFLLRPIK2                                                    4381680\n(UniMod:1)ADRPAIQLIDEEK2                                               16335785\n(UniMod:1)ADSRDPASDQMQHWK3                                             50734624\n(UniMod:1)ADYSSLTVVQLK2                                                 1069145\n(UniMod:1)AEASIEK1                                                     63096800\n```\n\n\n:::\n:::\n\n\n### Filtering: Remove highly missing precursors\n\nWe keep peptides that were observed at last 3 times out of the $n\n= 9$ samples, so that we can estimate the peptide characteristics. \nWe tolerate the following proportion of NAs:\n$\\text{pNA} = \\frac{(n - 3)}{n} = 0.666$, so we keep peptides that\nare observed in at least 66.6% of the samples, which corresponds to one treatment condition. This is an arbitrary\nvalue that may need to be adjusted depending on the experiment and the\ndata set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnObs <- 3\nn <- ncol(spikein_dia[[\"precursors\"]])\n\n(spikein_dia <- filterNA(spikein_dia, i = \"precursors\", pNA = (n - nObs) / n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 10 sets:\n\n [1] B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA: SummarizedExperiment with 32885 rows and 1 columns \n [2] B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA: SummarizedExperiment with 33526 rows and 1 columns \n [3] B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA: SummarizedExperiment with 32434 rows and 1 columns \n ...\n [8] B000306_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA_3: SummarizedExperiment with 32861 rows and 1 columns \n [9] B000310_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA_3: SummarizedExperiment with 32144 rows and 1 columns \n [10] precursors: SummarizedExperiment with 36292 rows and 9 columns \n```\n\n\n:::\n:::\n\n\n\n### Filter one-hit wonders\n\nHere, we remove proteins that can only be found by one peptide, as such proteins may not be trustworthy.\n\n1. We first calculate how many distinct peptides map to each protein (`Protein.id`). We use the stripped precursor sequence, i.e. sequence of the base peptide for this purpose. \n\n2. We store this information in the row data of the precursors assay\n\n3. We filter precursors of one-hit wonder proteins.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for peptides per protein\npepsPerProtDf <- spikein_dia[[\"precursors\"]] |> \n    rowData() |> \n    data.frame() |>\n    dplyr::select(\"Stripped.Sequence\", \"Protein.Ids\") |>\n    group_by(Protein.Ids) |>\n    mutate(pepsPerProt = Stripped.Sequence |>\n               unique() |> length()\n           ) #1.\n\nrowData(spikein_dia[[\"precursors\"]])$pepsPerProt <- pepsPerProtDf$pepsPerProt #2. \n\nspikein_dia <- filterFeatures(spikein_dia, \n                              ~ pepsPerProt > 1, \n                              keep = TRUE) #3.\n```\n:::\n\n\n## Log-transformation \n\nWe typically start a MS-based proteomics data analysis by log2 transforming the intensities. We illustrate the rationale\nusing the spike-in data. For this, we perform a short data\nmanipulation pipeline:\n\n1. We use `longForm()` to convert the `QFeatures` object into a long\ntable, where each row contains the quantitative information about\none observation, in which column, row and set it was found. Long\ntables are particularly useful for manipulating data with the\n`tidyverse` ecosystem, namely with `ggplot2` for visualisation.\n`longForm()` also allows to include annotations, and we here\ninclude `Mixture` and `TechRepMixture` for filtering and colouring.\n2. `longForm()` returns a `DataFrame` which we convert to a\n`data.frame`.\n3. We filter the data to keep only the data from precursor \"(UniMod:1)ADSRDPASDQMQHWK3\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- longForm(spikein_dia, colvars = colnames(colData(spikein_dia))) |> ## 1.\n  data.frame() |> ## 2.\n  filter(rowname == \"(UniMod:1)ADSRDPASDQMQHWK3\") ## 3.\n```\n:::\n\n\nNext, we visualise the data using `ggplot2`. We will show the\nintensities and log2-intensities for one of the precursors, ADSRDPASDQMQHWK3, in\nfunction of the known spike-in ratio. We first define a common\nplot from which we generate two plots, one without and the other with\nlog2 transformation of the quantitative values.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![MS-data is heteroskedastic, but log transformation achieves homoskedasticity. Peptide intensities (left) or log2 intensities (right) are plotted in function of spike-in concentration.](01-dataprocessing-median-sum_files/figure-html/basics_log_plot-1.png){width=672}\n:::\n:::\n\n\nWe can see that the variation around the mean for each concentration slightly increases as the mean increases. This is known as heteroskedasticity.\nWe will later see that `msqrob2` assumes that variance of the error\nis equal across the different conditions. Upon,\nlog2-transformation we can see that the problem of unequal variability\nis solved.\n\nAnother advantages of log2-transformation is that it provides a scale\nthat directly relates to biological interpretation. In biology, a\nchange induced by some condition often results in a fold change in\nconcentration. Interestingly, the log2 fold change (logFC), which is\nthe log2 of the ratio between two conditions, is identical to the\ndifference between the log of each condition.\n\n$$log_2FC_{b-a} = log_2b - log_2a = log_2 \\frac{b}{a}$$\n\nThis simplifies the modelling since the effects are now additive and\nit provides a straightforward interpretation, i.e. a logFC of 1 means that the\nabundances are on average $2\\times$ higher in $b$ than in $a$, a logFC of 2\nmeans an average increase of $4\\times$, for instance.\nAlso, note that the averages calculated at the log2-scale have the interpretation of log2-transformed geometric means. \n\nWe perform log2-transformation with `logTransform()` from the\n`QFeatures` package. We use `base = 2` and store the result in a new summarized experiment named `precursors_log`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia <- logTransform(spikein_dia, \n                            base = 2, \n                            i = \"precursors\", \n                            name = \"precursors_log\")\n```\n:::\n\n\n## Normalisation {#sec-norm}\n\nThe most common objective of MS-based proteomics experiments is to\nunderstand the biological changes in protein abundance between\nexperimental conditions. However, changes in measurements between\ngroups can be caused due to technical factors. For instance, there are\nsystematic fluctuations from run-to-run that shift the measured\nintensity distribution. We can this explore as follows:\n\n1. We extract the sets containing the log transformed data. This is \nperformed using `QFeatures`' 3-way subsetting^[We will explain this\nwith more details at the end of the [summarisation step](#sec-summarisation)].\n2. We use `longForm()` to convert the `QFeatures` object into a long\ntable, including `condition` and `concentration` for filtering and\ncolouring.\n3. We visualise the density of the quantitative values within each\nsample. We colour each sample based on its spike-in condition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia[, , \"precursors_log\"] |> #1.\n  longForm(colvars = c( \"rep\", \"condition\")) |>  #2. \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + #3.\n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density() +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nEven in this clean synthetic data set (same yeast background with some spiked UPS proteins), the marginal precursor intensity\ndistributions across samples are not well aligned. Ignoring this\neffect will increase the noise and reduce the statistical power of the\nexperiment, and may also, in case of unbalanced designs, introduce\nconfounding effects that will bias the results.\n\nThere are many ways to perform the normalisation, e.g.  median centering is a popular choice. \nIf we subtract the sample median at the log scale from each precursor log2 intensity, this basically boils down to calculating log-ratio's between the precursor intensity and its sample median. \nHere, we choose to work with offsets, that are chosen in such a way so that the distributions are centered around the location of a reference sample. E.g. the median of the sample medians. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnf_log <- assay(spikein_dia[[\"precursors_log\"]]) |> \n  colMedians(na.rm = TRUE)\nnf_log <- nf_log - median(nf_log)\n\nspikein_dia <- sweep( #4. Subtract log2 norm factor column-by-column (MARGIN = 2)\n  spikein_dia,\n  MARGIN = 2,\n  STATS = nf_log,\n  i = \"precursors_log\",\n  name = \"precursors_norm\"\n)\n```\n:::\n\n\nWe explore the effect of the total normalisation in the subsequent plot. \n\n\nFormally, the function applies the following operation on each sample\n$i$ across all precursors $p$:\n\n$$\ny_{ip}^{\\text{norm}} = y_{ip} - \\log_2(nf_i)\n$$\n\nwith $y_ip$ the log2-transformed intensities and $nf_i$ the log2-transformed norm factor. Upon normalisation, we can see\nthat the distribution of the $y_{ip}^{\\text{norm}}$ nicely overlap (using the same code as above)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia[, , \"precursors_norm\"] |>\n  longForm(colvars = c( \"rep\", \"condition\")) |> \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + \n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density() +\n  labs(subtitle = \"Normalised log2 precursor intensities\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nNote, that many different normalisation factors are proposed in the literature. We will evaluate different normalisation strategies in the tutorial session. \n\n## Summarisation\n\nThe objective of summarisation (also referred to as aggregation) is to\nsummarise the precursor-level intensities into a protein expression value.\nWe illustrate the motivation for summarisation using all peptide-level data for\none of the spiked UPS proteins. \nThe different precursors are shown on the\nx axis and plot their log2 normalised intensities across samples on y\naxis. All the points belonging to the same sample are linked through a\ngrey line.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Precursor-level data for UPS protein P16083. Each point represents a measured peptide within a sample, and the points are connected when they belong to the same sample.](01-dataprocessing-median-sum_files/figure-html/basics_summarise-1.png){width=576}\n:::\n:::\n\n\n1. We can see that data for a protein can consist of many precursors, \nhence the need for summarisation.\n2. We observe that different precursors have different intensities \nwithin the same sample (same line). This is because different\nprecursors have different properties and hence differ in their ionisation\nefficiency, which will influence the detectability in the MS \n([Challenges]).\n3. The precursor identification are inconsistent between groups of \ninterest. We can see the low-concentration group (condition a, red)\ndisplay more missing values than the high-concentration group\n(condition e, blue). Moreover, which value is missing depends on\nthe precursor characteristics. All the precursors found in the\nlow-concentration group are the most intense precursors in the high\nconcentration group.\n4. We also often find outliers, for instance, due to misidentification or fluctuations during MS acquisition.\n5. These data also suggest pseudo-replication. The precursor intensities\nin one same sample (dots connected by a line) are correlated, i.e.\nthey more alike than the precursor intensities between samples\n(the lines do not perfectly align). \n\nThe fact that different precursors have different intensities (2.), may\nbe inconsistently identified (3.) and/or quantified (4.), and show\nsample correlations (5.) can lead to bias if we use simple\nsummarisation approaches such as summing or averaging the precursor\nintensities for each sample. Instead, we will resort to more advanced\nsummarisation approaches to accommodate for these issues.\n\n\nHere, we summarise the precursor-level data into protein intensities\nthrough simple median summarisation. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n(spikein_dia <- aggregateFeatures(\n  spikein_dia, i = \"precursors_norm\", \n  name = \"proteins\",\n  fcol = \"Protein.Ids\", \n  fun = matrixStats::colMedians,\n  na.rm = TRUE\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 13 sets:\n\n [1] B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA: SummarizedExperiment with 32885 rows and 1 columns \n [2] B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA: SummarizedExperiment with 33526 rows and 1 columns \n [3] B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA: SummarizedExperiment with 32434 rows and 1 columns \n ...\n [11] precursors_log: SummarizedExperiment with 35880 rows and 9 columns \n [12] precursors_norm: SummarizedExperiment with 35880 rows and 9 columns \n [13] proteins: SummarizedExperiment with 3187 rows and 9 columns \n```\n\n\n:::\n:::\n\n\nNote that all the links between precursors and proteins are kept^[In\nfact, this is also true for the previous transformation where the\nprecursors are linked across sets.]. This come particularly handy when\nwe want to extract all the data from one protein, P16083 for\ninstance. This can be performed using the 3-way indexing. Every\n`QFeatures` object contains one or more sets, each characterised by\nmultiple rows (precursors or proteins) and multiple columns (samples).\nTherefore, `QFeatures` can subset data based on one or more of these\nindices, `data[set_k, feature_i, sample_j]`. The first entry will\nsubset particular features. This can be the name of a precursor (e.g.\n`KGMVAAWSQR2`) or the name of a protein (`UPS|P16083ups|NQO2_HUMAN_UPS`).\nThe second entry selects the samples columns of interest. The third\nentry selects the sets of interest. If an entry is left blank, all the\ncorresponding features, samples or sets will be selected. Let's\nextract all the data (all samples and all sets) related to the ups protein\n(`UPS|P16083ups|NQO2_HUMAN_UPS`).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia[\"UPS|P16083ups|NQO2_HUMAN_UPS\", , ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 13 sets:\n\n [1] B000254_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio02_DIA: SummarizedExperiment with 11 rows and 1 columns \n [2] B000258_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio04_DIA: SummarizedExperiment with 12 rows and 1 columns \n [3] B000262_Ap_6883_EXT-765_DIA_Yeast_UPS2_ratio08_DIA: SummarizedExperiment with 14 rows and 1 columns \n ...\n [11] precursors_log: SummarizedExperiment with 14 rows and 9 columns \n [12] precursors_norm: SummarizedExperiment with 14 rows and 9 columns \n [13] proteins: SummarizedExperiment with 1 rows and 9 columns \n```\n\n\n:::\n:::\n\nWe finally evaluate the marginal distribution of the aggregated protein summaries. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia[, , \"proteins\"] |>\n  longForm(colvars = c( \"rep\", \"condition\")) |> \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + \n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density() +\n  theme_minimal() +\n   labs(subtitle = \"Normalised log2 protein intensities\")\n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nThe data processing is complete.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(spikein_dia)\n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n# Data exploration\n\nData exploration aims to highlight the main sources of variation in\nthe data prior to data modelling and can pinpoint to outlying or\noff-behaving samples. \n\nA common approach for data exploration is to\nperform dimension reduction, such as Multi Dimensional Scaling (MDS).\nWe will first extract the set to explore along the sample annotations\n(used for plot colouring).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse <- getWithColData(spikein_dia, \"proteins\")\n```\n:::\n\n\nWe then use the `scater` package to compute and plot the PCA. For\ntechnical reasons, it requires `SingleCellExperiment` class object,\nbut these can easily be generated from a `SummarizedExperiment`\nobject. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nse <- runMDS(as(se, \"SingleCellExperiment\"), exprs_values = 1)\n```\n:::\n\n\nWe can now explore the data structure while coloring for the factor of\ninterest, here `condition`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotMDS(se, colour_by = \"condition\", shape_by = \"rep\") \n```\n\n::: {.cell-output-display}\n![MDS visualisation of the spike-in data set. Each point represents a sample and is coloured by the spike-in condiion.](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-32-1.png){width=768}\n:::\n:::\n\n\nThis plot reveals interesting information. First, we see that the\nsamples are nicely separated according to their spike-in condition.\nInterestingly, the conditions are sorted by the concentration.\n\nThe plot also reveals one outlying sample for spike-in condition 4. \n\n\n# Data Modeling (Robust Regression){#sec-modelling}\n\n\nWe model the preprocessed data to answer biologically relevant\nquestions. As described above, each sample has been synthetically\ncreated to contain a constant human background where E. coli lysates\nwere spiked in at five different concentration. Each sample\npreparation has been replicated four times. \nSo, the key question is \"can our\nmodel retrieve the proteins that have been spiked in across the\nconditions?\" Moreover, since we know the expected protein abundance in\neach sample, we will also be able to assess how accurate the model can\nestimate the average fold changes between spike-in conditions.\n\n## Sources of variation\n\nIn this experimental design, we can model a single source of variation: \nspike-in concentration^[Note that we have the spike-in concentration\nencoded in two ways. `ratio` is encoded as a numerical value\nand provides the actual ratio for UPS on 10 for yeast. `condition`\nis encoded as a factor, meaning that every concentration is regarded\nas an independent group. We will use the latter encoding as most\ncommon research questions consist of group-wise comparisons. The\nmodelling of concentration as a numeric will be discussed in a\n[dedicated section](#sec-numeric_model)]. All remaining sources of\nvariability, e.g. pipetting errors, MS run to run variability, etc\nwill be lumped in the residual variability (error term).\n\n**Spike-in condition effects**: we model the source of variation\ninduced by the experimental treatment of interest as a fixed\neffect, which we consider non-random, i.e. the treatment effect is\nassumed to be the same in repeated experiments, but it is unknown\nand has to be estimated.\n\nWhen modelling a typical label-free experiment at the protein level, \nthe model boils down to the following linear model:\n\n$$\ny_i = \\mathbf{x}^T_i \\boldsymbol{\\beta} + \\epsilon_i\n$$\n\nwith $y_i$ the $\\log_2$-normalised and summarised protein intensities in sample $i$;\n$\\mathbf{x}_i$ a vector with the covariate pattern for the sample\nencoding the intercept, spike-in condition^[Categorical\nvariables are encoded using dummy coding.], or other experimental factors; $\\boldsymbol{\\beta}$ the\nvector of parameters that model the association between the covariates\nand the outcome; and $\\epsilon_i$ the residuals reflecting variation\nthat is not captured by the fixed effects. Note that $\\mathbf{x}_i$\nallows for a flexible parameterisation of the treatment beyond a\nsingle covariate, i.e. including a 1 for the intercept, continuous and\ncategorical variables as well as their interactions. We assume the\nresiduals to be independent and identically distributed (i.i.d)\naccording to a normal distribution with zero mean and constant\nvariance, i.e. $\\epsilon_{i} \\sim N(0,\\sigma_\\epsilon^2)$, that can\ndiffer from protein to protein.\n\nIn R, this model is encoded using the following simple formula^[We\ndon't need to specify the intercept as R automatically adds it during\nmodel estimation. you can explicitly add it using `~ 1 + ...`, you can\nalso suppress it using `~ 0 + `. When an intercept is included, one of\nthe groups is defined as the reference group and its corresponding\nmodel parameter is absorbed in the intercept. The residuals don't need\nto be specified as they are part of the model estimation process.]:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- ~ condition + rep\n```\n:::\n\n\n## Model estimation{#sec-msqrob}\n\nWe estimate the model with `msqrob()`. The function takes the\n`QFeatures` object, extracts the quantitative values from the\n`\"proteins\"` set generated during summarisation, and fits a simple\nlinear model with `condition` as covariate, which are\nautomatically retrieved from `colData(spikein_dia)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia <- msqrob(\n  spikein_dia,  i = \"proteins\",\n  formula = model,\n  robust = TRUE\n)\n```\n:::\n\n\nWe enable M-estimation (`robust = TRUE`) for improved robustness\nagainst outliers. \n\nThe fitting results are available in the `msqrobModels` column of the\n`rowData`. More specifically, the modelling output is stored in the\n`rowData` as a `statModel` object, one model per row (protein). We\nwill see in a later section how to perform statistical inference on\nthe estimated parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels <- rowData(spikein_dia[[\"proteins\"]])[[\"msqrobModels\"]]\nmodels[1:3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$D6VTK4\nObject of class \"StatModel\"\nThe type is \"rlm\"\nThere number of elements is 5 \n\n$O13297\nObject of class \"StatModel\"\nThe type is \"rlm\"\nThere number of elements is 5 \n\n$O13329\nObject of class \"StatModel\"\nThe type is \"fitError\"\nThere number of elements is 5 \n```\n\n\n:::\n:::\n\n\n## Statistical inference{#sec-inference}\n\nWe can now convert the research question \"do the spike-in\nconditions affect the protein intensities?\" into a statistical\nhypothesis. \n\nIn other words, we need to translate this question in a null and alternative hypothesis on a single model parameter or a linear combination of model parameters, which is also referred to with a [contrast](#sec-inference).\n\nTo aid defining contrasts, we will visualise the experimental design using the `ExploreModelMatrix` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvd <- ExploreModelMatrix::VisualizeDesign(\n    sampleData =  colData(spikein_dia),\n    designFormula = model,\n    textSizeFitted = 4\n)\nvd$plotlist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nThis plot shows that the average protein $\\log_2$ intensity for condition2 is modelled by `(Intercept)`, for the `condition4` group by `(Intercept) + condtion4` and for the `condition8` group by `(Intercept) + condtion8`.\n \nHence, to assess differential abundance of proteins between spike-in conditions, we will have to assess all pairwise combinations between the spike-in groups, which leads to 3 different contrasts, i.e. the log2 fold change between ratio 4 and ratio 2, $\\log_2 FC_{4-2} = (Intercept + condition4) - Intercept = condition4$, the log2 fold change between ratio 8 and ratio 2, $\\log_2 FC_{8-2} = (Intercept + condition8) - Intercept = condition8$, and the log2 fold change between ratio 8 and ratio 4, $\\log_2 FC_{8-4} = (Intercept + condition8) - (Intercept+condition4) = condition8 - condition4$. \n\n### Hypothesis testing \n\nAs shown above, the average difference in log2 intensity between\ncondition 4 and 2 after correcting for the lab effect is\n`condition4`. This combination of parameters is also called a\ncontrast. Thus, we assess the following null hypothesis for this\ncontrast: `condition4 = 0` with our statistical test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast <- \"condition4 = 0\"\n```\n:::\n\n\n`makeContrast()` converts the hypothesis into a formal contrast matrix\nwith parameter names as rows and hypotheses in columns^[Note, that we only need to specify the names of the model parameters that are involved in the contrast when using the make contrast function. The hypothesisTest function below will then subset the relevant part from the model output. Also, note that the contrast matrix in this example is trivial. However, we will\n[later](#sec-multiple_contrasts) show how to asses multiple hypotheses\nat once and then the contrast matrix consists of multiple\ncolumns, with one column for each contrast].\nThe function `makeContrast()` also has an argument `parameterNames` in which we have to provide all parameter names involved in the contrast. \nSince we already used the `VisualizeDesign` we have a design matrix with all parameter names in the columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(L <- makeContrast(\n  \"condition4 = 0\",\n   parameterNames = colnames(vd$designmatrix)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            condition4\n(Intercept)          0\ncondition4           1\ncondition8           0\nrep2                 0\nrep3                 0\n```\n\n\n:::\n:::\n\n\nWe can now test our null hypothesis using `hypothesisTest()` which\ntakes the `QFeatures` object with the fitted model and the contrast we\njust built. `msqrob2` automatically applies the hypothesis\ntesting to all proteins in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia <- hypothesisTest(spikein_dia, i = \"proteins\", contrast = L)\n```\n:::\n\n\nThe results are stored in the set containing the model, here\n`proteins`. We retrieve the results from the `rowData`.\nNote, that for this spike-in study we know the ground truth, so we also add variable `isUPS` to indicate if the protein is spiked \n(UPS).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninference <- rowData(spikein_dia[[\"proteins\"]])$condition4 \nhead(inference)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             logFC        se       df          t      pval   adjPval\nD6VTK4 -0.28547626 0.1802291 6.483028 -1.5839631 0.1606140 0.9880929\nO13297 -0.24223280 0.1949703 6.561589 -1.2424090 0.2566467 0.9880929\nO13329          NA        NA       NA         NA        NA        NA\nO13539  0.11794083 0.2066624 5.695995  0.5706932 0.5899923 0.9880929\nO13563  0.09499004 0.3928488 6.396735  0.2417980 0.8165032 0.9887898\nO13585 -0.20038974 0.1858998 6.245431 -1.0779448 0.3209222 0.9880929\n```\n\n\n:::\n:::\n\n\nNote, that missing values can occur because data modelling\nresulted in a `fitError` (the [advanced vignette](#sec-fiterror)\ndescribes how to deal with proteins that could not be fit).\n\nThe results also include an adjusted p-value for each protein $j$ to\ncorrect for multiple testing using the Benjamini-Hochberg False\nDiscovery Rate (FDR) method, which represents an estimate of the\nminimum FDR at which the test result for protein $j$ is considered\nsignificant, i.e. the expected fraction of false positives that are\nreported in the shortest top list of the most significant proteins\nthat include protein $j$.\n\n### Volcano plots\n\nA volcano plot is a common visualisation that provides an overview of\nthe hypothesis testing results, plotting the $-\\log_{10}$ p-value^[Note, that upon this transformation a value of 1 represents a p-value of 0.1, 2 a p-value of 0.01, 3 a p-value of 0.001, etc.] as a function of\nthe estimated log fold change. Volcano plots can be used to highlight\nthe most interesting proteins that have large fold changes and/or are\nhighly significant. We can use the table above directly to build a\nvolcano plot using `ggplot2` functionality. We also highlight which\nproteins are UPS standards, known to be differentially abundant by\nexperimental design.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05 \nvolcano <- plot_volcano(inference, significance_level = alpha) + \n  labs(subtitle = paste0(colnames(L), \" = 0\"))\nvolcano \n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nNote, that the log fold changes are nicely around the real log2 fold change: $\\log_2(4/2) = 1$ \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignif <- inference |>\n  filter(adjPval < alpha) |>\n  arrange(pval)\nknitr::kable(signif)\n```\n\n::: {.cell-output-display}\n\n\n| logFC| se| df|  t| pval| adjPval|\n|-----:|--:|--:|--:|----:|-------:|\n\n\n:::\n:::\n\n\nNote, that we return many true positives and one false positive. \n\n### Heatmap{#sec-heatmaps}\n\nWe can explore the quantitative data of the significant proteins using\na heatmap. First, we select the names of the proteins that were \ndeclared significant between condition A and condition B and extract\ntheir quantitative data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsig <- inference |> \n  filter(adjPval < alpha) |> \n  arrange(pval) |> \n  rownames()\n```\n:::\n\n\nNext, we extract the quantitative data and scale by rows^[The\n`scales()` function aligns the means and the centered standard\ndeviations by column. Since we want to scale by row, we need to\ntranspose (`t())`) before scaling and transpose back after scaling.\nScaling the data will remove changes in feature intensities that are\ncaused by uninteresting changes in ionisation efficiency.] with\n`assay()`. We will create a heatmap using the `ComplexHeatmap`\npackage, which enables heatmap annotations. We will annotate the\nheatmap using our model variables `condition` and `lab`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse <- getWithColData(spikein_dia, \"proteins\")\nquants <- t(scale(t(assay(se[sig,]))))\ncolnames(quants) <- paste0(\"con\", se$condition,\"_rep\",se$rep)\nannotations <- columnAnnotation(\n  condition = se$condition\n)\n```\n:::\n\n\nWe now make the heatmap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234) ## annotation colours are randomly generated by default\nheatmap <-  Heatmap(\n quants, \n name = \"log2 intensity\",\n top_annotation = annotations,\n column_title = paste0(contrast)\n)\nheatmap\n```\n\n::: {.cell-output-display}\n![Heatmap of the proteins that are significantly differentially abundant between condition b and condition a.](01-dataprocessing-median-sum_files/figure-html/basics_heatmap-1.png){width=480}\n:::\n:::\n\n\n## All contrasts \n\nWith the createPairwiseContrast function we can make all pairwise contrasts for a model. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n(allHypotheses <- createPairwiseContrasts(\n  model, colData(spikein_dia), \"condition\"\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"condition8 - condition4 = 0\" \"condition4 = 0\"             \n[3] \"condition8 = 0\"             \n```\n\n\n:::\n\n```{.r .cell-code}\n(L <- makeContrast(\n  allHypotheses,\n  parameterNames = colnames(vd$designmatrix)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            condition8 - condition4 condition4 condition8\n(Intercept)                       0          0          0\ncondition4                       -1          1          0\ncondition8                        1          0          1\nrep2                              0          0          0\nrep3                              0          0          0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspikein_dia <- hypothesisTest(spikein_dia, \n                              i = \"proteins\", \n                              contrast = L,\n                              overwrite = TRUE)\n```\n:::\n\n\n### List with significant differentially abundant proteins\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninference_list <- lapply(colnames(L),\n  function(contrast, row_data){\n    row_data[[contrast]] |>\n      arrange(pval)\n    }, \n  row_data = rowData(spikein_dia[[\"proteins\"]])\n  )\nnames(inference_list) <- colnames(L)\n```\n:::\n\n\n\n```{.r .cell-code}\nfor (contrast in colnames(L)) #3. \n{\n  cat(\"**Contrast:**\", contrast, \"= 0 (\", nrow(inference_list[[contrast]] |> filter(adjPval < alpha)), \"significant proteins)\\n\\n\") #8.\n  print(kable(inference_list[[contrast]] |> filter(adjPval < alpha) |> arrange(pval)) |>\n          kable_styling(full_width = FALSE) |>\n          scroll_box(height = \"250px\")\n      ) #9.\n  cat(\"\\n\\n\\n---\\n\\n\") #10.\n}\n```\n\n**Contrast:** condition8 - condition4 = 0 ( 0 significant proteins)\n\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:250px; \"><table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> logFC </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> se </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> df </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> t </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> pval </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> adjPval </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> -----: </td>\n   <td style=\"text-align:right;\"> --: </td>\n   <td style=\"text-align:right;\"> --: </td>\n   <td style=\"text-align:right;\"> --: </td>\n   <td style=\"text-align:right;\"> ----: </td>\n   <td style=\"text-align:right;\"> -------: </td>\n  </tr>\n</tbody>\n</table></div>\n\n\n---\n\n**Contrast:** condition4 = 0 ( 0 significant proteins)\n\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:250px; \"><table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> logFC </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> se </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> df </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> t </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> pval </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> adjPval </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n   <td style=\"text-align:right;\"> NA </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> -----: </td>\n   <td style=\"text-align:right;\"> --: </td>\n   <td style=\"text-align:right;\"> --: </td>\n   <td style=\"text-align:right;\"> --: </td>\n   <td style=\"text-align:right;\"> ----: </td>\n   <td style=\"text-align:right;\"> -------: </td>\n  </tr>\n</tbody>\n</table></div>\n\n\n---\n\n**Contrast:** condition8 = 0 ( 14 significant proteins)\n\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:250px; \"><table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\">  </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> logFC </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> se </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> df </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> t </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> pval </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> adjPval </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P06732ups&amp;#124;KCRM_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.923112 </td>\n   <td style=\"text-align:right;\"> 0.1454911 </td>\n   <td style=\"text-align:right;\"> 6.561589 </td>\n   <td style=\"text-align:right;\"> 13.218071 </td>\n   <td style=\"text-align:right;\"> 0.0000057 </td>\n   <td style=\"text-align:right;\"> 0.0170621 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> P05318 </td>\n   <td style=\"text-align:right;\"> 2.388345 </td>\n   <td style=\"text-align:right;\"> 0.2165840 </td>\n   <td style=\"text-align:right;\"> 6.561589 </td>\n   <td style=\"text-align:right;\"> 11.027338 </td>\n   <td style=\"text-align:right;\"> 0.0000178 </td>\n   <td style=\"text-align:right;\"> 0.0206306 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P62937ups&amp;#124;PPIA_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 2.060685 </td>\n   <td style=\"text-align:right;\"> 0.1819691 </td>\n   <td style=\"text-align:right;\"> 6.281719 </td>\n   <td style=\"text-align:right;\"> 11.324370 </td>\n   <td style=\"text-align:right;\"> 0.0000206 </td>\n   <td style=\"text-align:right;\"> 0.0206306 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P69905ups&amp;#124;HBA_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.785793 </td>\n   <td style=\"text-align:right;\"> 0.1905746 </td>\n   <td style=\"text-align:right;\"> 6.561589 </td>\n   <td style=\"text-align:right;\"> 9.370573 </td>\n   <td style=\"text-align:right;\"> 0.0000490 </td>\n   <td style=\"text-align:right;\"> 0.0274391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P15559ups&amp;#124;NQO1_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.576657 </td>\n   <td style=\"text-align:right;\"> 0.1673522 </td>\n   <td style=\"text-align:right;\"> 6.481233 </td>\n   <td style=\"text-align:right;\"> 9.421187 </td>\n   <td style=\"text-align:right;\"> 0.0000511 </td>\n   <td style=\"text-align:right;\"> 0.0274391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;Q15843ups&amp;#124;NEDD8_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 2.328575 </td>\n   <td style=\"text-align:right;\"> 0.2423886 </td>\n   <td style=\"text-align:right;\"> 6.121481 </td>\n   <td style=\"text-align:right;\"> 9.606781 </td>\n   <td style=\"text-align:right;\"> 0.0000645 </td>\n   <td style=\"text-align:right;\"> 0.0274391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P12081ups&amp;#124;SYHC_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.559971 </td>\n   <td style=\"text-align:right;\"> 0.1580947 </td>\n   <td style=\"text-align:right;\"> 5.846347 </td>\n   <td style=\"text-align:right;\"> 9.867318 </td>\n   <td style=\"text-align:right;\"> 0.0000732 </td>\n   <td style=\"text-align:right;\"> 0.0274391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P16083ups&amp;#124;NQO2_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.767354 </td>\n   <td style=\"text-align:right;\"> 0.2045310 </td>\n   <td style=\"text-align:right;\"> 6.561589 </td>\n   <td style=\"text-align:right;\"> 8.641006 </td>\n   <td style=\"text-align:right;\"> 0.0000805 </td>\n   <td style=\"text-align:right;\"> 0.0274391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P63165ups&amp;#124;SUMO1_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.530260 </td>\n   <td style=\"text-align:right;\"> 0.1663105 </td>\n   <td style=\"text-align:right;\"> 6.121665 </td>\n   <td style=\"text-align:right;\"> 9.201225 </td>\n   <td style=\"text-align:right;\"> 0.0000827 </td>\n   <td style=\"text-align:right;\"> 0.0274391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;Q06830ups&amp;#124;PRDX1_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.423005 </td>\n   <td style=\"text-align:right;\"> 0.1706653 </td>\n   <td style=\"text-align:right;\"> 6.560160 </td>\n   <td style=\"text-align:right;\"> 8.337985 </td>\n   <td style=\"text-align:right;\"> 0.0001002 </td>\n   <td style=\"text-align:right;\"> 0.0274391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P62988ups&amp;#124;UBIQ_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.881767 </td>\n   <td style=\"text-align:right;\"> 0.2181467 </td>\n   <td style=\"text-align:right;\"> 6.319447 </td>\n   <td style=\"text-align:right;\"> 8.626153 </td>\n   <td style=\"text-align:right;\"> 0.0001005 </td>\n   <td style=\"text-align:right;\"> 0.0274391 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P61626ups&amp;#124;LYSC_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.791196 </td>\n   <td style=\"text-align:right;\"> 0.2313783 </td>\n   <td style=\"text-align:right;\"> 6.311433 </td>\n   <td style=\"text-align:right;\"> 7.741418 </td>\n   <td style=\"text-align:right;\"> 0.0001902 </td>\n   <td style=\"text-align:right;\"> 0.0476045 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> P40055 </td>\n   <td style=\"text-align:right;\"> -1.735717 </td>\n   <td style=\"text-align:right;\"> 0.2314379 </td>\n   <td style=\"text-align:right;\"> 6.405306 </td>\n   <td style=\"text-align:right;\"> -7.499710 </td>\n   <td style=\"text-align:right;\"> 0.0002126 </td>\n   <td style=\"text-align:right;\"> 0.0491311 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UPS&amp;#124;P02144ups&amp;#124;MYG_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.600400 </td>\n   <td style=\"text-align:right;\"> 0.1833595 </td>\n   <td style=\"text-align:right;\"> 5.358308 </td>\n   <td style=\"text-align:right;\"> 8.728213 </td>\n   <td style=\"text-align:right;\"> 0.0002292 </td>\n   <td style=\"text-align:right;\"> 0.0491869 </td>\n  </tr>\n</tbody>\n</table></div>\n\n\n---\n\n### Volcanoplots \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvolcanoplots <- lapply(inference_list, plot_volcano)\n    \nfor (contrast in colnames(L))\nprint(\n  volcanoplots[[contrast]] + \n    labs(subtitle=paste0(contrast,\" = 0\")) \n)\n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-48-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-48-3.png){width=672}\n:::\n:::\n\n### Heatmaps\n\nWe conduct heatmaps for the significant metabolites for each contrast. \n\n1. We first extract the normalised assay `metabolites_norm` along with its colData. \n2. We make an empty list `heatmaps` to store the plots.\n3. We will loop over the column names of the contrast matrix `L`\n4. We extract the names of the significant features for contrast `i`\n5. We extract the quant data for the significant metabolites\n6. We extract annotation\n7. We make the heatmap using the quants data. We do not cluster columns (samples) to keep them together according to the design.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheatmaps <- lapply(colnames(L),\n                   function(contrast, se, alpha)\n                   {\n                     sig <- rowData(se)[[contrast]] |> \n                       filter(adjPval < alpha) |> \n                       rownames()\n                     quants <- t(scale(t(assay(se[sig,]))))\n                     colnames(quants) <- paste0(\"con\", se$condition,\"_rep\",se$rep)\n                     annotations <- columnAnnotation(condition = se$condition)\n                     set.seed(1234) ## annotation colours are randomly generated by default\n                     return(\n                       Heatmap(\n                       quants, \n                       name = \"log2 intensity\",\n                       top_annotation = annotations, \n                       column_title = paste0(contrast, \" = 0\")\n                       )\n                     )\n                   },\n                   se = getWithColData(spikein_dia, \"proteins\"),\n                   alpha = alpha)\nnames(heatmaps) <- colnames(L)\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (contrast in colnames(L))\n  print(heatmaps[[contrast]])\n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-50-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-50-3.png){width=672}\n:::\n:::\n\n## Assess performance\n\nNote, that the evaluations in this section are typically not possible on real experimental data. \nIndeed, we are using a spike-in dataset so we know the ground thruth: all human UPS proteins are differentially abundant (DA) between the conditions and the yeast proteins are non-DA.\n\n### Real Fold changes \n\nAs this is a spike-in study with known ground truth, we can also plot the log2 fold change distributions against the expected values, in this case 0 for the yeast proteins and the difference of the log concentration for the spiked-in UPS standards. We first create a small table with the real values.\n\n1. We extract the levels from factor condition\n2. We convert then into a number as they refer to the real ratio\n3. We log2-transform them \n4. We calculate all pairwise differences between log2 transformed ratio's to obtain the log2 fold changes\n\nWe use a similar operation to construct the name of the corresponding contrast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(realLogFC <- data.frame(\n    logFC = colData(spikein_dia)$condition |> \n        levels() |> # 1. \n        as.double() |> # 2. \n        log2() |> # 3. \n        combn(m=2, FUN = diff), #4.\n    comparison = colData(spikein_dia)$condition |> \n        levels() |> \n        combn(m=2, FUN= function(x) paste0(x[2],\" - \",x[1])) |>\n        recode(\"4 - 2\" = \"4\", \n               \"8 - 2\" = \"8\")\n    )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  logFC comparison\n1     1          4\n2     2          8\n3     1      8 - 4\n```\n\n\n:::\n:::\n\n\n### True and false positives\n\nAll human UPS proteins are differentially abundant (DA) between the conditions and the yeast proteins are non-DA.\nWe make a new variable spikein in the inference_list. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (contrast in names(inference_list))\n{\n  inference_list[[contrast]] <- \n    inference_list[[contrast]] |> \n    mutate(Protein = rownames(inference_list[[contrast]]), \n           spikein = grepl(\"UPS\", Protein) |>\n             as.factor() |>\n             recode(\"FALSE\" = \"yeast\", \n                    \"TRUE\" = \"ups\")\n    )\n}\n```\n:::\n\n\nWe can now assess the number of false positives and true positives at the significance level $\\alpha = 0.05$. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(inference_list, \n       function(inference) inference |> \n         filter(adjPval < alpha) |> \n         pull(spikein) |>\n         table())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      condition8 - condition4 condition4 condition8\nyeast                       0          0          2\nups                         0          0         12\n```\n\n\n:::\n:::\n\n\n### log-fold changes \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogFC <- sapply(colnames(L), \n                function(contrast, inference_list, realLogFC) inference_list[[contrast]] |> \n                  filter(!is.na(logFC)) |>\n                  ggplot(aes(x = spikein, y = logFC, color= spikein)) + \n                  geom_boxplot() +\n                  theme_bw() + \n                  scale_color_manual(\n                    values = c(\"grey20\", \"firebrick\"), \n                    name = \"\",\n                    labels = c(\"yeast\", \"ups\")\n                    ) + \n                  geom_hline(yintercept = 0, color=\"grey20\") +\n                  geom_hline(yintercept = realLogFC |> \n                               filter(comparison == gsub(contrast, pattern=\"condition\", replacement=\"\")) |>\n                               pull(logFC),\n                             color=\"firebrick\") +\n                  labs(subtitle = paste0(contrast,\" = 0\"))\n                ,\n                inference_list = inference_list,\n                realLogFC = realLogFC\n                )\nlogFC\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`condition8 - condition4`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$condition4\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-54-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$condition8\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-54-3.png){width=672}\n:::\n:::\n\n\n### volcano-plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvolcanoplots <- lapply(inference_list, plot_volcano)\n    \nfor (contrast in colnames(L))\nprint(\n  volcanoplots[[contrast]] + \n    aes(color=spikein, shape = adjPval < alpha) + \n    scale_color_manual(\n      values = c(\"grey20\", \"firebrick\"), \n      name = \"spikein\",\n      labels = c(\"yeast\", \"ups\")\n      ) +\n    labs(subtitle=paste0(contrast,\" = 0\"), shape = paste0(\"FDR < \",alpha)) + \n    geom_vline(xintercept = realLogFC |> \n               filter(comparison == str_replace_all(contrast,\"condition\",\"\")) |> \n               pull(logFC), color = \"firebrick\")\n)\n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-55-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-55-3.png){width=672}\n:::\n:::\n\n\n### True positive - False Discovery Proportion plots\n\nWe first make a function to plot the true positives rate, i.e. the fraction of real DA proteins that are picked up in function the false discovery proportion (FDP), i.e. the fraction of false positives on the total number of DA proteins that are returned in a toplist, which we can calculate in a spike-in experiment because we have ground truth data.\n\n1. We order the pvalues according to their significance\n2. We calculate the TPR for all features that are equally or more significant than the current feature. \n3. We calculate the FDP for all features that are equally or more significant than the current feature. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntprFdp <- function(pval, tp) {\n  ord <- order(pval) #1.\n  data.frame(\n    tpr = cumsum(tp[ord]) / sum(tp), #2. \n    fdp = cumsum(!tp[ord]) / 1:length(tp) #3.\n  )\n}\n```\n:::\n\n\nWe merge all results\n1. We first add a variable with the contrast to each list \n2. We calculate the tprFdp for each \n3. We plot the results upon merging the lists via rbind. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (contrast in names(inference_list)) \n  inference_list[[contrast]] <- inference_list[[contrast]] |> \n  mutate(\n          contrast = contrast, #1.\n          tprFdp(pval, spikein == \"ups\")) #2. \n\n\nggplot(inference_list |> do.call(what=rbind), #3.\n       aes(x = fdp, y = tpr, color = contrast)) +\n  geom_path(linewidth = 1) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"grey\") +\n  geom_vline(xintercept = 0.05, linetype = \"dotted\") + # 5% FDR line\n  labs(\n    title = \"TPR vs FDP Performance\",\n    x = \"False Discovery Proportion (FDP)\",\n    y = \"True Positive Rate (Sensitivity)\",\n    color = \"Contrast\"\n  ) +\n  theme_bw() +\n  theme(legend.position = \"bottom\") \n```\n\n::: {.cell-output-display}\n![](01-dataprocessing-median-sum_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n\n",
    "supporting": [
      "01-dataprocessing-median-sum_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}