createPairwiseContrasts <- function(formula, coldata, var, ridge = FALSE, nullHypothesis = " = 0") {
    params <- .getParamNames(formula, coldata, var, ridge)
    out <- combn(params, 2)
    out <- paste0(out[2, ], " - ", out[1, ])
    hasIntercept <- attr(terms(formula), "intercept")
    isFirst <- labels(terms(formula))[[1]] == var
    if (hasIntercept && isFirst)
        out <- c(out, params)
    paste0(out, nullHypothesis)
}

createOneVersusAllContrasts <- function(formula, coldata, var,
                                        ridge = FALSE,
                                        nullHypothesis = " = 0") {
    params <- .getParamNames(formula, coldata, var, ridge)
    averages <-
      sapply(0:length(params), function(i) {
        paramSum <- ifelse(i == 0, paste(params, collapse = " + ") , paste(params[-i], collapse = " + "))
        paste0("(", paramSum, ") / ", length(params))
    })
    paste0(c("",params), " - ", averages, nullHypothesis)
}

.getParamNames <- function(formula, coldata, var, ridge) {
    params <- lme4::nobars(formula) |>
        model.matrix(, data = coldata) |>
        colnames()
    params <- params[grepl(var, params)]
    if (length(params) == 0)
        stop(sQuote(var), " not found as fixed effect in formula.")
    if (any(grepl("[:]", params)))
        stop("You cannot automatically create pairwise contrasts for a variable involved in an interaction.")
    if (ridge) params <- paste0("ridge", params)
    unique(params)
}

.makeResultColumns <- function(contrast, resultsColumnNamePrefix) {
    if (is.null(colnames(contrast))) {
        if (resultsColumnNamePrefix == "")
            resultsColumnNamePrefix <- "msqrobResults"
        if (ncol(contrast) > 1)
            colnames(contrast) <- seq_len(ncol(contrast))
    }
    paste0(resultsColumnNamePrefix, colnames(contrast))
}

.getMsqrob2Results <- function(object, row_var) {
    if (!row_var %in% colnames(rowData(object)))
        stop(
            sQuote(row_var), "is not found in the rowData of the ",
            "SummarizedExperiment object. Make sure you set the ",
            "same 'contrast' and 'resultsColumnNamePrefix' as for ",
            "'hypothesisTest()'."
        )
    rowData(object)[[row_var]]
}


##' Function to collect the inference tables generated by the msqrob2
##' statistical inference workflow.
##'
##' @param object A `SummarizedExperiment` object containing model
##'    inference performed by `hypothesisTest()`.
##' @param contrast A numeric `matrix` providing the contrast matrix
##'     used during model estimation.
##' @param resultsColumnNamePrefix A `character(1)` providing the
##'     prefix used when running `hypothesisTest()`.
##' @param combine A `logical(1)` indicating whether the result tables
##'     should be combined in a single table (default) or return as a
##'     list of tables. When combined, two new variables are created:
##'     1. `contrast`tells from which contrast (column of the `contrast`
##'     matrix) the results where obtained; 2. `feature` provides the
##'     name of the modelled feature (this information is taken from
##'     the rownames of the tables, but this are made unique upon
##'     combining).
msqrobCollect <- function(object, contrast, resultsColumnNamePrefix = "",
                           combine = TRUE) {
    resultCols <- .makeResultColumns(contrast, resultsColumnNamePrefix)
    out <- lapply(resultCols, .getMsqrob2Results, object = object)
    names(out) <- resultCols
    if (combine) {
        for (i in names(out)) {
            out[[i]]$contrast <- i
            out[[i]]$feature <- rownames(out[[i]])
        }
        out <- do.call(rbind, out)
    }
    out
}

msqrobRefit <- function(object, formula, i, subset, fcol, name,
                        modelColumnName = "msqrobModels", ...) {
    seti <- getWithColData(object, i)
    setj <- getWithColData(object, name)
    if (any(!subset %in% rowData(seti)[[fcol]]))
        stop("Some entries in 'subset' not found in '", fcol,
             "' (rowData of set '", i, "')")
    setjRefit <- msqrobAggregate(
        seti[rowData(seti)[[fcol]] %in% subset, ],
        formula = formula, fcol = fcol, modelColumnName = modelColumnName,
        ...
    )
    rowData(setj)[[modelColumnName]][subset] <-
        rowData(setjRefit)[[modelColumnName]][subset]
    modelsNew <- rowData(setj)[[modelColumnName]]
    hlp <- limma::squeezeVar(
        var = vapply(modelsNew, getVar, numeric(1)),
        df = vapply(modelsNew, getDF, numeric(1))
    )
    for (ii in seq_along(modelsNew)) {
        modelsNew[[ii]]@varPosterior <- as.numeric(hlp$var.post[ii])
        modelsNew[[ii]]@dfPosterior <- as.numeric(hlp$df.prior + getDF(modelsNew[[ii]]))
    }
    rowData(object[[name]])[[modelColumnName]] <- modelsNew
    object
}



## Norm factors for median normalisation 
# 1. Calculates the sample medians of the intensity assay of summarised experiment `i` in qfeatures object `qf` 
# 2. Defines the log norm factor by subtracting the median of the sample medians from each sample median,  so as to center the intensities of all samples around the median intensity in the experiment. 

nf_log_med <- function(qf, i, base = 2){
  nf_log <- assay(qf[[i]]) |> 
    colMedians(na.rm = TRUE) #1.
  nf_log <- nf_log - median(nf_log) #2. 
  return(nf_log)
}


## Total loading normalisation
# DIA-NN for instance by default corrects for the total loading, i.e. the sum of all raw intensities of reliable precursors. Particularly, they scale the precursor intensities to the loading of a reference sample, i.e. the median loading over all samples. 

# This function 
 
#1. extracts the log-transformed intensities according with base `base` in summarized experiment `i` of QFeatures object `qf`
#2. calculates the total log-transformed loading, by 
#a. converting the intensities back to the original scale
#b. calculating the total loading in each run (column)
#c. transforming it back to the log-scale 
#3. rescaling it to the median loading

nf_log_tot <- function(qf, i, base = 2){
  log_val <- assay(qf[[i]]) #1. 
  tot_log_loading <- base^log_val |> #2.a
    colSums(na.rm = TRUE) |> #2.b
    log(base = base) #2.c
  nf_log <- tot_log_loading - median(tot_log_loading) #3.
  
  return(nf_log)
}

## Median of Ratio's 

#The bulk RNA-seq tool DESeq 2 for instance uses the median of ratio's approach. 
# We provide a function to calculate these log-norm factors that 

# 1. We first create a pseudo-reference sample (row-wise mean of log2 
#intensities, which corresponds to the log2 transformed geometric 
#mean). 
#2. Calculate the log2 ratios of each sample w.r.t. the 
#pseudo-reference 
#3. Subsequently take the column wise median of these log2 ratios to 
#obtain the sample based normalisation factor on the log2 scale.

nf_log_medrat <- function(qf, i, base = 2){
  pseudoref <- assay(qf[[i]]) |> 
    rowMeans(na.rm = TRUE) #1. 
 
  nf_log <- sweep(
    assay(qf[[i]]), 
    MARGIN = 1, 
    pseudoref) |> #2. Subtract the row means row-by-row (MARGIN = 1)
    colMedians(na.rm = TRUE)  #3. Calculate the column median 
  
  return(nf_log)
}

get_searchengine_nf <- function(qf, i, nf_name, log = TRUE, base = 2) 
{
  #nf_name = "Normalisation.Factor" for DIA-NN and "EG_NormalizationFactor" for spectronaut
  out <- sapply(colnames(qf[[i]]), function(ii, qf, ids, nf_name) rowData(qf[[ii]])[ids,nf_name], qf = qf, ids = rownames(qf[[i]]), nf_name = nf_name)
  if (log) out <- -log(out, base = base)
  rownames(out) <- rownames(qf[[i]])
  return(out)
}



# Volcano plot
#1. We calculate the adjusted significance level for the original p-values that corresponds to the nominal FDR significance level.
#2. We make the volcano plot by plotting statistial significance, i.e. -log10(pvalues), in function of the effect size or biological relevance, i.e. log2 FC or log2 RDA. We color the dots according to their significance, black if the adjusted p-value is higher than the FDR significance level and red if the adjusted p-value is lower than the FDR significance level. 
#3. We add a line with the adjusted significance level that corresponds to the original p-values
#4. We add the dots to the plot.
#5. We set the layout of the plot (theme, labels, etc.)

plot_volcano <- function(results_table, effectsize = "logFC", adjPval = "adjPval", pval = "pval", significance_level = 0.05, significance_colors= c("FALSE" = "black", "TRUE" = "red"), opacity = .5)
{

#adjAlpha <- significance_level*mean(results_table[[adjPval]] < significance_level, na.rm = TRUE) #1.

volcano_out <- 
  results_table |> 
  filter(!is.na(.data[[adjPval]])) |> 
  ggplot( 
          aes(x = .data[[effectsize]],
              y = -log10(.data[[pval]]), col = .data[[adjPval]] < significance_level)) + #2.
  
#  geom_hline(yintercept = -log10(adjAlpha)) + #3.
  
  geom_point(size = 1, alpha = opacity) + #4. 
  
  theme_bw() + #5. 
  ylab("-log10(p-value)") +
  scale_color_manual(values = significance_colors, breaks = c("TRUE", "FALSE")) +
  labs(color=paste0("FDR < ",significance_level))
return(volcano_out)
}



